# Generated by Django 4.2.16 on 2024-11-01 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0002_recipe_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
