# Generated by Django 4.2.16 on 2024-10-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
