# Generated by Django 4.2.16 on 2025-02-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0003_alter_comment_options_remove_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
