# Generated by Django 4.2.16 on 2025-02-21 00:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0004_alter_comment_options_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
