# Generated by Django 4.2.16 on 2025-02-21 00:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0006_remove_recipe_image_recipe_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='image'),
        ),
    ]
