# Generated by Django 4.2.16 on 2025-02-22 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodblog', '0008_alter_recipe_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='foodblog.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foodblog.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='foodblog.category'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvoted_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvoted_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
